import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header} from "./components/HomePage/Header";
import Footer from "./components/HomePage/Footer";
import Navbar from "./components/HomePage/NavBar";
import CartProvider from "./components/Provider";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import { WishlistProvider } from "../context/wishListContext"; 
import { ShippingProvider } from "../context/ShippingContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Furniture Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <CartProvider>
            <WishlistProvider> {/* Wrapped with WishlistProvider */}
            <ShippingProvider>
              <div className="max-w-[1920px] mx-auto">
                <Header />
                <Navbar />
                <Toaster />
                {children}
                <Footer />
              </div>
              </ShippingProvider>
            </WishlistProvider>
          </CartProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
